### ISSUE TITLE
[Suggestion] Block specific words or phrases in the lobby

### ISSUE THREAD

**Issue by nicco1690** [udu3324/Poinpow#12]
People have been advertising in the public chat recently to get around the `/ad` limitations. As a result, the feature in this mod for blocking ads is no longer as effective because you'll still see people advertising in the chat. 

I could just use a chat mod, but I don't want to turn it off every time I join a server, and I don't think there are any that can detect when you are on a Minehut server and not the lobby, let alone enable/disable it when on a specific server.

It would probably be better if you able to add custom blocked words/phrases as well.

**Comment by udu3324** [comment]
Noted.

**Comment by udu3324** [comment]
Added in 1.4.1, 1.3.1, and 1.2.5
