### ISSUE TITLE
[Suggestion] Allow specific rank lobby-ads

### ISSUE THREAD

**Issue by modderongithub** [udu3324/Poinpow#27]
Sometimes when you're looking for a server to play on you would be looking at ads. However, if you was to enable ads you would get flooded by bots and high-rank players shoving their pay-to-win server in your face constantly. What could solve this is a setting to allow ads from certain ranks - say, default + VIP (or whatever the player decides, ignoring the cosmetic event tags).

I'm not sure if this would be possible to filter out certain ranks due to the cosmetic tags, but at the very least you would be able to filter between default/old-rank players and subscription-rank players due to chat colour.

**Comment by udu3324** [comment]
Sure. I'll see if i can add it this spring break.

**Comment by modderongithub** [comment]
> Sure. I'll see if i can add it this spring break.

Alright, thanks!

**Comment by udu3324** [comment]
There is progress in the latest commit.

**Comment by udu3324** [comment]
Added in [1.6.3](https://github.com/udu3324/Poinpow/releases/tag/1.6.3)
